void makeBookTmp(bookNode* parent, char bookName[100]);
bookNode* createBook(char bookName[100]);
void destroyTreeBooks(bookNode *head);
bookNode* removeBook(bookNode* currPtr, int bookIdValue);
void makeBook(bookNode* head, char bookName[100]);
void saveDataBooks(bookNode* head);
void saveOtherDataBooks();
bookNode* getBook(bookNode* currPtr, char bookPar[256]);
void searchBook(bookNode* head, char nameOfBook[100]);
//void loadData(bookNode* head);